-- Supabase SQL to create chat_messages table for Realtime Chat
-- You can run this in the Supabase Dashboard -> SQL Editor

-- Drop the old table if it exists (since we're changing id from UUID to BIGINT)
DROP TABLE IF EXISTS public.chat_messages;

CREATE TABLE public.chat_messages (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "senderId" TEXT NOT NULL,
  "receiverId" TEXT,
  "senderName" TEXT,
  "senderRole" TEXT,
  "message" TEXT NOT NULL,
  "conversationId" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "readAt" TIMESTAMPTZ,
  "messageType" TEXT DEFAULT 'text'
);

-- Enable Realtime for this table by adding it to the supabase_realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_messages;

-- Set up Row Level Security (RLS)
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- Create appropriate RLS policies
-- Note: Since we are using MongoDB for auth and these users are essentially "anonymous" 
-- from Supabase's auth perspective (or if you are using custom JWTs, replace 'true' with appropriate auth checks).
-- We'll enable access for all requests. If you have custom JWT auth set up, you would check auth.uid().
CREATE POLICY "Enable read access for all" ON "public"."chat_messages"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable insert for all" ON "public"."chat_messages"
AS PERMISSIVE FOR INSERT
TO public
WITH CHECK (true);
